/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
    UserDtoToJSONTyped,
} from './UserDto';

/**
 * 
 * @export
 * @interface CategoryDto
 */
export interface CategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CategoryDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CategoryDto
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryDto
     */
    color?: string;
    /**
     * 
     * @type {UserDto}
     * @memberof CategoryDto
     */
    user?: UserDto;
}

/**
 * Check if a given object implements the CategoryDto interface.
 */
export function instanceOfCategoryDto(value: object): value is CategoryDto {
    return true;
}

export function CategoryDtoFromJSON(json: any): CategoryDto {
    return CategoryDtoFromJSONTyped(json, false);
}

export function CategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'color': json['color'] == null ? undefined : json['color'],
        'user': json['user'] == null ? undefined : UserDtoFromJSON(json['user']),
    };
}

export function CategoryDtoToJSON(json: any): CategoryDto {
    return CategoryDtoToJSONTyped(json, false);
}

export function CategoryDtoToJSONTyped(value?: CategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'type': value['type'],
        'color': value['color'],
        'user': UserDtoToJSON(value['user']),
    };
}

