/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionDto } from './TransactionDto';
import {
    TransactionDtoFromJSON,
    TransactionDtoFromJSONTyped,
    TransactionDtoToJSON,
    TransactionDtoToJSONTyped,
} from './TransactionDto';

/**
 * 
 * @export
 * @interface PageResponseTransactionDto
 */
export interface PageResponseTransactionDto {
    /**
     * 
     * @type {Array<TransactionDto>}
     * @memberof PageResponseTransactionDto
     */
    data?: Array<TransactionDto>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTransactionDto
     */
    pageNum?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTransactionDto
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTransactionDto
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTransactionDto
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PageResponseTransactionDto interface.
 */
export function instanceOfPageResponseTransactionDto(value: object): value is PageResponseTransactionDto {
    return true;
}

export function PageResponseTransactionDtoFromJSON(json: any): PageResponseTransactionDto {
    return PageResponseTransactionDtoFromJSONTyped(json, false);
}

export function PageResponseTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TransactionDtoFromJSON)),
        'pageNum': json['pageNum'] == null ? undefined : json['pageNum'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'count': json['count'] == null ? undefined : json['count'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PageResponseTransactionDtoToJSON(json: any): PageResponseTransactionDto {
    return PageResponseTransactionDtoToJSONTyped(json, false);
}

export function PageResponseTransactionDtoToJSONTyped(value?: PageResponseTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TransactionDtoToJSON)),
        'pageNum': value['pageNum'],
        'pageSize': value['pageSize'],
        'count': value['count'],
        'totalPages': value['totalPages'],
    };
}

