spring:
  datasource:
    url: ${RENDER_DB_URL}
    username: ${RENDER_DB_USERNAME}
    password: ${RENDER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
      use_sql_comments: false
      format_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${RENDER_KEYCLOAK_API}

server:
  port: 8088
